### ISSUE TITLE
Please change the name of this project

### ISSUE THREAD

**Issue by aslakhellesoy** [hackhat/cucumberry#1]
Cucumber Limited (the company behind Cucumber) has a commercial product called [Cucumber Pro](https://cucumber.pro/)

We're in the process of trademarking it.

I strongly recommend you change the name.

**Comment by hackhat** [comment]
Mine is not a brand or similar is just a small project for cucumber js and node js. 
I have to think about this because involves a lot of changes: github, npm...

**Comment by jbpros** [comment]
Hi!

As Aslak (creator of Cucumber) pointed out, we (Cucumber Ltd) are running a product called Cucumber Pro, built on Node. It integrates with all flavours of Cucumber (including Cucumber.js). End users need to install a plugin alongside Cucumber in order to use it. That plugin is ready for [Cucumber Ruby](https://rubygems.org/gems/cucumber-pro) and [Cucumber-JVM](http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22info.cukes%22%20AND%20a%3A%22cucumber-pro%22). The JavaScript version is on its way and we planned on releasing it under the name _cucumber-pro_ just like its Ruby and JVM cousins.

Can you please rename your project in order to avoid any confusion? That would be really appreciated!

If you need any assistance doing that, I'd be happy to help.

Cheers,

Julien, author of Cucumber.js.

**Comment by hackhat** [comment]
Renamed to cucumberry in https://github.com/hackhat/cucumberry/commit/be8569a6e6d77e08e28f5668592f41d1a9d7eec4

**Comment by hackhat** [comment]
Also npm is available: https://www.npmjs.com/package/cucumber-pro

**Comment by jbpros** [comment]
Thanks a lot @hackhat, we really appreciate it. And thanks for your contribution!

**Comment by hackhat** [comment]
I should thank you for the wonderful cucumber project!

**Comment by jbpros** [comment]
Well I'm glad you find it useful :)

**Comment by plumpNation** [comment]
7 years later. Great conversation. Kudos to you all.
